project/controllers/SpecialityController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\Model;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use app\models\forms\CalculateCostForm;
use app\models\repositories\VsRepository;
use app\models\repositories\StudyOptionRepository;
use app\models\repositories\EducationVariantRepository;
use app\models\repositories\EducationTechnologyRepository;
use app\models\repositories\SpecialitySubjectsRepository;
use app\models\repositories\ApplicationRepository;
use app\models\repositories\AppPassedSubjectsRepository;
use app\models\repositories\StudyCostRepository;
use app\models\PageSplitting;

class SpecialityController extends Controller
{

	private $countApplicationsOnPage = 10;
	
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['calculate-cost', 'show-passed-subjects', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
					[
						'actions' => ['index'],
						'allow' => true,
                        'roles' => ['admin'],
					]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'show-passed-subjects' => ['post'],
                ],
            ],
        ];
    }
	
	public function actionIndex() 
	{
		$page = (int) Yii::$app->request->get('page', 1);
		if($page <= 0) {
			throw new \yii\web\NotFoundHttpException('Извините, но запрашиваемая Вами страница не найдена');
		}
		$appRepository = new ApplicationRepository();
		//В том случае, если page превышает допустимое значение, при использовании PageSplitting будет выброшено исключение throw new \yii\web\NotFoundHttpException
		$pages = new PageSplitting($appRepository, $this->countApplicationsOnPage, $page);
		return $this->render('index', [
			'materials' => $pages->getCurrentMaterial(),
			'pages' => $pages->getPagination(),
		]);
	}
	
	public function actionView() 
	{
		$app = (int) Yii::$app->request->get('num');
		if($app <= 0) {
			throw new NotFoundHttpException('Извините, но запрашиваемая Вами страница не найдена');
		}
		$appRepository = new ApplicationRepository();
		$appPSRepository = new AppPassedSubjectsRepository();
		$specSubRepository = new SpecialitySubjectsRepository();
		$application = $appRepository->getOne($app, true);
		if(!$application) {
			throw new NotFoundHttpException('Извините, но запрашиваемая Вами страница не найдена');
		}
        if(!\Yii::$app->user->can('fullViewUsers', ['identity' => $application['idUser']])) {
			throw new ForbiddenHttpException('Вам не разрешено просматривать данную заявку');
		}
		$specialitySubjects = $specSubRepository->getSpSubjects($application['idSpeciality']);
		$passedSubjects = $appPSRepository->getForApplication($app);
		return $this->render('view', [
			'application' => $application,
			'specialitySubjects' => $specialitySubjects,
			'passedSubjects' => $passedSubjects,
		]);
	}

    public function actionCalculateCost()
    {
		if(!\Yii::$app->user->can('admin')) { //все, кроме админа могут заполнять лишь одну заявку!!!
			$appRepository = new ApplicationRepository();
			if($appRepository->getCount(['idUser' => Yii::$app->getSession()->get('__id')])) {
				Yii::$app->getSession()->setFlash('warning', 'Вы уже заполняли заявку на поступление. Вы можете просматривать заявку в вашем профиле, переходя по соответствующей ссылке');
				return $this->redirect(Yii::$app->urlManager->createUrl(['user/profile', 'num' => Yii::$app->params['userSettings']['diffBetweenId'] + Yii::$app->session->get('__id')]));
			}
		}
		$model = new CalculateCostForm();
        $vs = new VsRepository();
        $so = new StudyOptionRepository();
        $ev = new EducationVariantRepository();
        $et = new EducationTechnologyRepository();
        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $app = new ApplicationRepository();
            if($model->soPassed) {
                $answer = $app->addOneWithPassedSubjects($model);
            } else {
                $answer = $app->addOne($model);
            }
            if($answer) {
                $appData = $app->getOne($answer, true);
                $sub = new SpecialitySubjectsRepository();
                $subjects = $sub->getSpSubjects($model->variantSpeciality, -1);
                $this->sendApplicationMail($appData, $subjects, $model);
                return $this->render('calculate-cost', [
                   'username' => $model->username,
                    'applicationSent' => true,
                ]);
            }
            else {
                Yii::$app->getSession()->setFlash('error', 'Извините, но при попытке отправить заявку возникла ошибка. Попробуйте отправить заявку позже.');
                return $this->refresh();
            }
        }
        $v = $vs->getAll();
        $s = $so->getAll();
        $e1 = $ev->getAll();
        $e2 = $et->getAll();
        if(!$v || !$s || !$e1 || !$e2) {
            throw new NotFoundHttpException();
        }
		$cost = (new StudyCostRepository())->getAll(true);
		return $this->render('calculate-cost', [
            'model' => $model,
            'speciality' => $v,
            'options' => $s,
            'variant' => $e1,
            'technology' => $e2,
            'user' => \Yii::$app->user->getIdentity(),
            'cost' => $cost,
			'applicationSent' => false,
		]);
    }

    public function actionShowPassedSubjects()
    {
        if(!Yii::$app->request->isAjax) {
            return json_encode("no access");
        }
        $sp = (int) Yii::$app->request->post('sp');
        if(!$sp || $sp < 1) {
            throw new NotFoundHttpException;
        }
        $rep = new SpecialitySubjectsRepository();
        $subjects = $rep->getSpSubjects($sp, 1);
        if(!$subjects) {
            return json_encode("no");
        } else {
            return json_encode($subjects);
        }
    }

    private function sendApplicationMail(array $appData, array $subjects, Model $model)
	{
        $passedSubjects = array();
        if($model->soPassed) {
            for($i=0, $lt = count($subjects); $i < $lt; $i++) {
                if(in_array($subjects[$i]['id'], $model->soPassed)) {
                    array_push($passedSubjects, $subjects[$i]);
                }
            }
        }
        $paidSubjectsCount = count($subjects) - count($passedSubjects);
        Yii::$app->mailer->compose('speciality/application', [
            'data' => $model,
            'application' => $appData,
            'subjects' => $subjects,
            'passedSubjects' => $passedSubjects,
            'paidSubjectsCount' => $paidSubjectsCount,
        ])->setFrom(Yii::$app->params['adminEmail'])
            ->setTo($model->email)
            ->setSubject('Подтверждение принятия заявки')
            ->send();
    }

}

project/controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use app\models\repositories\UserRepository;
use app\models\repositories\ApplicationRepository;
use app\models\forms\LoginForm;
use app\models\forms\RegistryForm;
use app\models\forms\PasswordResetRequestForm;
use app\models\forms\ResetPasswordForm;

class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'request-reset-password', 'reset-password'],
				'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
					[
						'actions' => ['request-reset-password', 'reset-password'],
						'allow' => true,
                        'roles' => ['?'],
					],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionProfile()
    {
        $num = ((int) Yii::$app->request->get('num')) - Yii::$app->params['userSettings']['diffBetweenId'];
        if($num <= 0) {
            throw new NotFoundHttpException;
        }
        $mat = (new UserRepository())->getOne($num, true);
		if(!$mat) {
            throw new NotFoundHttpException;
        }
        $mat['registDate'] = date("d.m.Y в H:i", $mat['registDate']);
        $applications = (new ApplicationRepository())->getAllWhere(['idUser' => $num]);
		return $this->render('user-one', [
            'material' => $mat,
			'applications' => $applications ? $applications : null,
        ]);
    }

	/*
		если пользователь уже залогинился, то просто пересылаем его на главную страницу
	*/
    public function actionLogin()
    {
        if(!Yii::$app->user->isGuest) {
			Yii::$app->getSession()->setFlash('success', 'Вы уже вошли на сайт. Если Вы желаете войти под другим логином, Вам необходимо сначала выйти.');
            return $this->goHome();
        }
        $userRep = new UserRepository();
        $model = new LoginForm();
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $userRep->getOneByAttrs(['login' => $model->username]);
            if(!$user || !$userRep->validatePassword($user, $model->password)) {
                $model->addError('password', 'Вы ввели не правильные данные при авторизации, исправьте.');
            }
            else {
                $userRep->createCurrCheck($user);
                Yii::$app->user->login($user, $model->rememberMe ? 3600*24*30 : 0);
                Yii::$app->getSession()->setFlash('success', 'Приветствуем Вас '.$model->username.' на нашем сайте.');
                return $this->goHome();
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
	
	/*
		Используется при регистрации
		Проверяет как форму целиком, так и поля login и email через Ajax
		В целях обеспечения правильной работы капчи при ajax-проверке полей используется отдельный сценарий формы - 'individual'
	*/
	public function actionSignIn()
	{
        if(!\Yii::$app->user->isGuest) {
            \Yii::$app->getSession()->setFlash('success', 'Вы уже вошли на сайт.');
			return $this->goHome();
        }
        $userRep = new UserRepository();
		$model = new RegistryForm();
        if(Yii::$app->request->isAjax) {
            $model->scenario = 'individual';
        }
        $load = $model->load(Yii::$app->request->post());
		if(Yii::$app->request->isAjax && $load) {
            /*echo json_encode("good");
            exit;*/
            Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($load && $model->validate() && $userRep->addOne($model)) {
            $model->sendMail();
            Yii::$app->getSession()->setFlash('success', true);
		}
        return $this->render('regist', [
            'model' => $model,
		]);
	}

	/*
		выполняется при запросе на изменение пароля
	*/
    public function actionRequestResetPassword()
    {
        $userRep = new UserRepository();
        $model = new PasswordResetRequestForm();
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $userRep->getOneByAttrs(['email' => $model->email]);
            if(!$user) {
                $model->addError('email', 'Пользователя с таким адресом электронной почты не существует!');
            }
            else {
                if($userRep->validResetToken($user->resetToken)) {
                    Yii::$app->getSession()->setFlash('warning', 'Проверьте также Вашу электронную почту, возможно Вы уже сделали данный запрос!');
                }
                else {
                    $token = $userRep->createResetToken($user);
                    if(!$token || !$model->sendMail($token)) {
                        Yii::$app->getSession()->setFlash('warning', 'Извините, но в настоящий момент Вы не можете сменить пароль. Попробуйте сделать это позже.');
                    }
                    else {
                        Yii::$app->getSession()->setFlash('success', 'На Вашу электронную почту высланы инструкции по смене пароля.');
                        return $this->goHome();
                    }
                }
            }
        }
        return $this->render('request-reset-password', [
            'model' => $model,
        ]);
    }

	/*
		В том случае, если не указан $token или пользователя с таким $token-ом нет - выбрасываем InvalidParamException, который выбрасывает BadRequestHttpException
		Если же время $token вышло, то выбрасываем обычное исключение, которое сообщает от том, что
			время $token вышло и нужно вновь сделать запрос и перекидывает на страницу user/request-reset-password
	*/
    public function actionResetPassword($token)
    {
        try {

            if(empty($token) || !is_string($token)) {
                throw new InvalidParamException('Должен быть обязательно указан параметр смены пароля.');
            }
			$userRep = new UserRepository();
			if(!$userRep->validResetToken($token)) {
				throw new \Exception('Вы должны сделать новый запрос на смену пароля');
			}
            $user = $userRep->getOneByAttrs(['resetToken' => $token]);
			if(!$user) {
				throw new InvalidParamException('Пользователя с указанным значением параметра не существует.');
			}
            $model = new ResetPasswordForm();
            if($model->load(Yii::$app->request->post()) && $model->validate() && $userRep->update($user, [ 'password' => $model->password, 'resetToken' => null])) {
                Yii::$app->getSession()->setFlash('success', 'Пароль успешно изменен');
                return $this->goHome();
            }
            return $this->render('reset-password', [
                'model' => $model,
            ]);

        } catch(InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        } catch(\Exception $e) {
            Yii::$app->getSession()->setFlash('warning', $e->getMessage());
            return $this->redirect(Yii::$app->urlManager->createUrl('user/request-reset-password'));
        }

    }

}

project/views/user/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h3>Войти на сайт</h3>

    <p>Пожалуйста введите Ваш логин и пароль:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "<div class=\"col-sm-1\">{label}</div>\n<div class=\"col-sm-5 col-md-3\">{input}</div>\n<div class=\"col-sm-6 col-md-8\">{error}</div>",
            'labelOptions' => ['class' => 'control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox() ?>

    <div class="form-group">
        <div class="col-xs-offset-1">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-success', 'name' => 'login-button']) ?>&nbsp;&nbsp;
			<a href="<?=\Yii::$app->urlManager->createUrl('user/request-reset-password') ?>" data-toggle="tooltip" data-placement="right" title="Нажмите, чтобы сменить пароль">Забыли пароль?</a>
		</div>
    </div>

    <?php ActiveForm::end(); ?>
	
</div>

project/views/user/regist.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\RegistryForm */

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-signin">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if(\Yii::$app->getSession()->getFlash('success')){ ?>
        <div class="col-lg-offset-1 col-lg-10">
            <p class="alert alert-success">
                Вы зарегистрировались под логином <?=Html::encode($model->username); ?>.
                Для того, чтобы войти на сайт, Вам необходимо авторизоваться.
            </p>
        </div>
    <?php } else{ ?>
		<div>
			<p>Для регистрации необходимо заполнить все поля:</p>

			<?php $form = ActiveForm::begin([
				'id' => 'regist-form',
				'options' => ['class' => 'form-horizontal'],
				'fieldConfig' => [
					'template' => "<div class=\"col-md-5 col-lg-2\">{label}</div>\n<div class=\"col-md-7 col-lg-5\">{input}</div>\n<div class=\"col-md-12 col-lg-5\">{error}</div>",
					'labelOptions' => ['class' => 'control-label'],
				],
			]); ?>

			<?= $form->field($model, 'username', ['enableAjaxValidation' => true])->textInput(['placeholder' => 'Введите Ваш логин']); ?>

			<?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Введите пароль']); ?>

			<?= $form->field($model, 'password2')->passwordInput(['placeholder' => 'Подтвердите пароль']); ?>

			<?= $form->field($model, 'email', ['enableAjaxValidation' => true])->input('email', ['placeholder' => 'Введите Ваш email']); ?>

			<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
				'template' => '<div class="row"><div class="col-md-4 captcha">{image}</div><div class="col-md-8">{input}</div></div>',
				'imageOptions' => [
					'data-toggle' => "tooltip", 
					'data-placement' => "top",
					'title' => 'Нажмите для смены изображения',
				]
			]) ?>

			<div class="form-group">
				<div class="col-lg-offset-1 col-lg-11">
					<?= Html::submitButton('Регистрация', ['class' => 'btn btn-success', 'name' => 'regist-button']) ?>
				</div>
			</div>

			<?php ActiveForm::end(); ?>
		</div>

    <?php } ?>

</div>

project/views/user/request-reset-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Запрос на изменение пароля';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-reset-password">

    <h1 class="text-center"><?= Html::encode($this->title) ?></h1>

    <?php if($message = \Yii::$app->getSession()->getFlash('warning')){ ?>

        <div class="col-lg-offset-1 col-lg-10">
            <p class="alert alert-warning"><?=Html::encode($message); ?></p>
        </div>

    <?php } else{ ?>
		<div class="row">
			<div class="col-sm-offset-3 col-sm-6">
				<div class="panel panel-warning">
					<div class="panel-heading">
						<p class="panel-title">Введите Ваш <strong>адрес электронной почты</strong>. На данный адрес будет выслано письмо с инмтрукциями по смене пароля.</p>
					</div>
					<div class="panel-body">
						
						<?php $form = ActiveForm::begin([
							'id' => 'request-reset-password-form',
							'fieldConfig' => [
								'labelOptions' => ['class' => 'control-label'],
							],
						]); ?>

						<?= $form->field($model, 'email')->input('email', ['placeholder' => 'Введите Ваш email']); ?>

						<div class="form-group">
							<div class="text-center">
								<?= Html::submitButton('Отправить', ['class' => 'btn btn-success', 'name' => 'reset-button']) ?>
							</div>
						</div>

						<?php ActiveForm::end(); ?>
						
					</div>
				</div>
			</div>
		</div>

    <?php } ?>

</div>

project/views/user/reset-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Смена пароля';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-login">

    <h1 class="text-center"><?= Html::encode($this->title) ?></h1>

    <?php if($message = \Yii::$app->getSession()->getFlash('warning')){ ?>

        <div class="col-lg-offset-1">
            <p class="bg-warning"><?=Html::encode($message); ?></p>
        </div>

    <?php }else{ ?>

        <div class="row">
			<div class="col-md-offset-3 col-md-6">
				<div class="panel panel-warning">
					<div class="panel-heading">
						<p class="panel-title">Введите новый пароль:</p>
					</div>
					<div class="panel-body">

						<?php $form = ActiveForm::begin([
							'id' => 'reset-password-form',
							'fieldConfig' => [
								'labelOptions' => ['class' => 'control-label'],
							],
						]); ?>

						<?= $form->field($model, 'password')->passwordInput(); ?>

						<?= $form->field($model, 'password2')->passwordInput(); ?>

						<div class="form-group">
							<div class="col-lg-offset-1 col-lg-11">
								<?= Html::submitButton('Сменить пароль', ['class' => 'btn btn-success', 'name' => 'reset-button']) ?>
							</div>
						</div>

						<?php ActiveForm::end(); ?>
					</div>
				</div>
			</div>
		</div>
    
	<?php } ?>

</div>

project/views/user/user-one.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Кабинет пользователя '.$material['login'];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user">

	<?php if($message = \Yii::$app->session->getFlash('warning')) { ?>
		<div>
			<p class="alert alert-warning text-center"><?= $message; ?></p>
		</div>
	<?php } ?>

    <h3><?=Html::encode($material['login']); ?></h3>

    <div class="row">

        <div class="col-sm-6">
            <p>Зарегистрировался: <?=Html::encode($material['registDate']); ?></p>
			<?php if($applications) { ?>
				<?php if(!\Yii::$app->user->can('admin')) { ?>
                <p>
					<a href="<?= \Yii::$app->urlManager->createUrl(['speciality/view', 'num' => $applications[0]['id']]) ?>" class="btn btn-success" data-toggle="tooltip" data-placement="right" title="Нажмите для просмотра заявки">Посмотреть заявку</a>
				</p>
                <?php } else { ?>
                    <p>Список заявок администратора</p>
                    <ul>
                        <?php for($i = 0, $lh = count($applications); $i < $lh; $i++) { ?>
                            <li>
                                <a href="<?= \Yii::$app->urlManager->createUrl(['speciality/view', 'num' => $applications[$i]['id']]) ?>" class="link">Заявка №<?php echo $i + 1; ?></a>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>
			<?php } ?>
		</div>
        <?php if(\Yii::$app->user->can('fullViewUsers', ['identity' => $material['id']])) { ?>
            <div class="col-sm-6">
                <p class="text-right">Email: <?=Html::encode($material['email']); ?></p>
            </div>
        <?php } ?>
    </div>

</div>