project/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

}

project/controllers/SpecialityController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\Model;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use app\models\forms\CalculateCostForm;
use app\models\repositories\VsRepository;
use app\models\repositories\StudyOptionRepository;
use app\models\repositories\EducationVariantRepository;
use app\models\repositories\EducationTechnologyRepository;
use app\models\repositories\SpecialitySubjectsRepository;
use app\models\repositories\ApplicationRepository;
use app\models\repositories\AppPassedSubjectsRepository;
use app\models\repositories\StudyCostRepository;
use app\models\PageSplitting;

class SpecialityController extends Controller
{

	private $countApplicationsOnPage = 10;
	
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['calculate-cost', 'show-passed-subjects', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
					[
						'actions' => ['index'],
						'allow' => true,
                        'roles' => ['admin'],
					]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'show-passed-subjects' => ['post'],
                ],
            ],
        ];
    }
	
	public function actionIndex() 
	{
		$page = (int) Yii::$app->request->get('page', 1);
		if($page <= 0) {
			throw new \yii\web\NotFoundHttpException('Извините, но запрашиваемая Вами страница не найдена');
		}
		$appRepository = new ApplicationRepository();
		//В том случае, если page превышает допустимое значение, при использовании PageSplitting будет выброшено исключение throw new \yii\web\NotFoundHttpException
		$pages = new PageSplitting($appRepository, $this->countApplicationsOnPage, $page);
		return $this->render('index', [
			'materials' => $pages->getCurrentMaterial(),
			'pages' => $pages->getPagination(),
		]);
	}
	
	public function actionView() 
	{
		$app = (int) Yii::$app->request->get('num');
		if($app <= 0) {
			throw new NotFoundHttpException('Извините, но запрашиваемая Вами страница не найдена');
		}
		$appRepository = new ApplicationRepository();
		$appPSRepository = new AppPassedSubjectsRepository();
		$specSubRepository = new SpecialitySubjectsRepository();
		$application = $appRepository->getOne($app, true);
		if(!$application) {
			throw new NotFoundHttpException('Извините, но запрашиваемая Вами страница не найдена');
		}
        if(!\Yii::$app->user->can('fullViewUsers', ['identity' => $application['idUser']])) {
			throw new ForbiddenHttpException('Вам не разрешено просматривать данную заявку');
		}
		$specialitySubjects = $specSubRepository->getSpSubjects($application['idSpeciality']);
		$passedSubjects = $appPSRepository->getForApplication($app);
		return $this->render('view', [
			'application' => $application,
			'specialitySubjects' => $specialitySubjects,
			'passedSubjects' => $passedSubjects,
		]);
	}

    public function actionCalculateCost()
    {
		if(!\Yii::$app->user->can('admin')) { //все, кроме админа могут заполнять лишь одну заявку!!!
			$appRepository = new ApplicationRepository();
			if($appRepository->getCount(['idUser' => Yii::$app->getSession()->get('__id')])) {
				Yii::$app->getSession()->setFlash('warning', 'Вы уже заполняли заявку на поступление. Вы можете просматривать заявку в вашем профиле, переходя по соответствующей ссылке');
				return $this->redirect(Yii::$app->urlManager->createUrl(['user/profile', 'num' => Yii::$app->params['userSettings']['diffBetweenId'] + Yii::$app->session->get('__id')]));
			}
		}
		$model = new CalculateCostForm();
        $vs = new VsRepository();
        $so = new StudyOptionRepository();
        $ev = new EducationVariantRepository();
        $et = new EducationTechnologyRepository();
        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $app = new ApplicationRepository();
            if($model->soPassed) {
                $answer = $app->addOneWithPassedSubjects($model);
            } else {
                $answer = $app->addOne($model);
            }
            if($answer) {
                $appData = $app->getOne($answer, true);
                $sub = new SpecialitySubjectsRepository();
                $subjects = $sub->getSpSubjects($model->variantSpeciality, -1);
                $this->sendApplicationMail($appData, $subjects, $model);
                return $this->render('calculate-cost', [
                   'username' => $model->username,
                    'applicationSent' => true,
                ]);
            }
            else {
                Yii::$app->getSession()->setFlash('error', 'Извините, но при попытке отправить заявку возникла ошибка. Попробуйте отправить заявку позже.');
                return $this->refresh();
            }
        }
        $v = $vs->getAll();
        $s = $so->getAll();
        $e1 = $ev->getAll();
        $e2 = $et->getAll();
        if(!$v || !$s || !$e1 || !$e2) {
            throw new NotFoundHttpException();
        }
		$cost = (new StudyCostRepository())->getAll(true);
		return $this->render('calculate-cost', [
            'model' => $model,
            'speciality' => $v,
            'options' => $s,
            'variant' => $e1,
            'technology' => $e2,
            'user' => \Yii::$app->user->getIdentity(),
            'cost' => $cost,
			'applicationSent' => false,
		]);
    }

    public function actionShowPassedSubjects()
    {
        if(!Yii::$app->request->isAjax) {
            return json_encode("no access");
        }
        $sp = (int) Yii::$app->request->post('sp');
        if(!$sp || $sp < 1) {
            throw new NotFoundHttpException;
        }
        $rep = new SpecialitySubjectsRepository();
        $subjects = $rep->getSpSubjects($sp, 1);
        if(!$subjects) {
            return json_encode("no");
        } else {
            return json_encode($subjects);
        }
    }

    private function sendApplicationMail(array $appData, array $subjects, Model $model)
	{
        $passedSubjects = array();
        if($model->soPassed) {
            for($i=0, $lt = count($subjects); $i < $lt; $i++) {
                if(in_array($subjects[$i]['id'], $model->soPassed)) {
                    array_push($passedSubjects, $subjects[$i]);
                }
            }
        }
        $paidSubjectsCount = count($subjects) - count($passedSubjects);
        Yii::$app->mailer->compose('speciality/application', [
            'data' => $model,
            'application' => $appData,
            'subjects' => $subjects,
            'passedSubjects' => $passedSubjects,
            'paidSubjectsCount' => $paidSubjectsCount,
        ])->setFrom(Yii::$app->params['adminEmail'])
            ->setTo($model->email)
            ->setSubject('Подтверждение принятия заявки')
            ->send();
    }

}

project/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

project/views/site/index.php
<?php

use yii\helpers\Html;

$this->title = 'Главная';
?>

<div class="site-index">

    <?php if($message = \Yii::$app->getSession()->getFlash('success')){ ?>

        <div class="row">
			<div class="col-lg-offset-1 col-lg-10">
				<p class="alert alert-success"><?=$message; ?></p>
			</div>
		</div>

    <?php } ?>

    <div class="jumbotron">
        <h1>Приветствуем Вас!</h1>

        <p class="lead">Вы зашли на сайт учебного заведения &lt;&lt;ZZZ&gt;&gt;.</p>

        <p>На нашем сайте Вы можете заполнить заявку на поступление.<br /> Выбирайте специальность, которая Вам наиболее интересна, и отправляйте анкету</p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-md-6">
                <p>Обучение платное. Его стоимость, а также продолжительность зависит от выбранной специальности</p>

                <p>Количество дисциплин зависит от выбранной Вами специальности</p>

                <p><strong class="text-warning">Обращаем Ваше внимание</strong>, что в том случае, если у Вас уже есть диплом о Высшем образовании,
                    Вы можете перезачесть часть дисциплин, сократив тем самым как срок, так и стоимость обучения</p>

                <p><a class="btn btn-success" href="<?=\Yii::$app->urlManager->createUrl(["speciality/calculate-cost"]); ?>">Заполнить заявку</a></p>
            </div>
        </div>

    </div>
</div>